spring:
  application:
    name: ebank-service-router

server:
  port: 8080

ebank-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:9000
    ServerListRefreshInterval: 15000